help:
	@echo "This Makefile contains only a 'clean' recipe:"
	@echo "   make clean"
	@echo "will remove all .png files, as well as pulse_table.csv and pulse_table.tex"

clean:
	$(RM) *.png pulse_table.csv pulse_table.tex
